# Generated by Django 5.1.7 on 2026-03-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stundet', '0002_contact_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_info',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
