# Generated by Django 5.1.7 on 2026-03-12 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stundet', '0004_registereduser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registereduser',
            old_name='zipp',
            new_name='zip_code',
        ),
    ]
